# generated by hamstersql
from sqlalchemy import text

import core

{{range .}}
# {{.ReturnTypeStr }}: {{.Doc}}
{{- if .Parameters}}
def {{.Properties.name}}(session{{range .Parameters}}, {{.}}{{end}}):
{{- else}}
def {{.Properties.name}}(session):
{{- end}}
    query = text("""
{{.SqlQuery}}
    """)
    params = {
{{- range .Parameters}}
        "{{.}}": {{.}},
{{- end}}
    }
    result = session.execute(query, params)
    {{- if eq .ReturnTypeStr "one"}}
    return core.convert_result_to_one_row(result)
    {{- end}}
    {{- if eq .ReturnTypeStr "many"}}
    return core.convert_result_to_many_rows(result)
    {{- end}}
    {{- if eq .ReturnTypeStr "affected"}}
    return core.convert_result_to_affected_rows(result)
    {{- end}}
    {{- if eq .ReturnTypeStr "scalar"}}
    return core.convert_result_to_scalar(result)
    {{- end}}
    {{- if eq .ReturnTypeStr "insert"}}
    return core.convert_result_to_insert_id(result)
    {{- end}}
    {{- if eq .ReturnTypeStr "none"}}
    return result
    {{- end}}

{{end}}
